-- Runs automatically the first time the Postgres container starts.
-- Enables pgvector. Table creation can live here or in SQLAlchemy models.
CREATE EXTENSION IF NOT EXISTS vector;

-- Reference schema (Claude Code can generate the real version via SQLAlchemy):
--
-- CREATE TABLE companies (
--   id                    BIGSERIAL PRIMARY KEY,
--   ticker                TEXT NOT NULL UNIQUE,
--   cik                   TEXT NOT NULL UNIQUE,
--   name                  TEXT NOT NULL,
--   sic                   TEXT,            -- SIC code, e.g. "7372"
--   sic_description       TEXT,            -- e.g. "Prepackaged Software"
--   state_of_incorporation TEXT,           -- e.g. "DE"
--   exchanges             TEXT,            -- comma-separated, e.g. "NASDAQ"
--   entity_type           TEXT             -- e.g. "Operating Company"
-- );
--
-- CREATE TABLE filings (
--   id           BIGSERIAL PRIMARY KEY,
--   company_id   BIGINT NOT NULL REFERENCES companies(id),
--   form_type    TEXT NOT NULL,            -- '10-K', '10-Q'
--   fiscal_year  INT,
--   url          TEXT NOT NULL,
--   filed_at     DATE,
--   UNIQUE (url)
-- );
--
-- CREATE TABLE chunks (
--   id          BIGSERIAL PRIMARY KEY,
--   filing_id   BIGINT REFERENCES filings(id) ON DELETE CASCADE,
--   chunk_index INT NOT NULL,
--   section     TEXT,
--   text        TEXT NOT NULL,
--   embedding   VECTOR(1536)
-- );
CREATE INDEX IF NOT EXISTS chunks_embedding_hnsw_idx
    ON chunks USING hnsw (embedding vector_cosine_ops);
--
-- CREATE TABLE conversations (
--   id         BIGSERIAL PRIMARY KEY,
--   title      TEXT,                          -- first question, truncated to 200 chars
--   created_at TIMESTAMPTZ DEFAULT now(),
--   updated_at TIMESTAMPTZ DEFAULT now()
-- );
--
-- CREATE TABLE messages (
--   id                BIGSERIAL PRIMARY KEY,
--   conversation_id   BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
--   seq               INT NOT NULL,           -- 0-based order within conversation
--   role              TEXT NOT NULL,          -- 'user' | 'assistant'
--   content           TEXT NOT NULL,          -- question or final answer text
--   created_at        TIMESTAMPTZ DEFAULT now(),
--   input_tokens      INT,                    -- assistant messages only
--   output_tokens     INT,
--   cache_read_tokens INT,
--   cache_write_tokens INT,
--   model             TEXT,
--   latency_ms        INT
-- );
